name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  github-token:
    description: 'Github token for authentication against the Github API'
    required: true
  max-artifacts:
    description: 'The maximum number of artifacts to keep in the repo (default = 10)'
    required: true
    default: 10
runs:
  using: 'node12'
  main: 'index.js'