name: 'Delete oldest artifacts'
description: 'This action delets the oldest artifacts in a repository. All artifacts that exceed the specified limit are removed.'
inputs:
  github-token:
    description: 'Github token for authentication against the Github API'
    required: true
  max-artifacts:
    description: 'The maximum number of artifacts to keep in the repo (default = 10, has to be >= 0)'
    required: true
    default: 10
runs:
  using: 'node12'
  main: 'dist/index.js'